services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    platform: linux/arm64     
    container_name: kasm
    privileged: true
    security_opt:
      - apparmor:rootlesskit
    environment:
      - KASM_PORT=443
      - DOCKER_HUB_USERNAME=USER
      - DOCKER_HUB_PASSWORD=PASS
      - DOCKER_MTU=1500
    volumes:
      - ./data:/opt
      - ./profiles:/profiles
      - /dev/input:/dev/input
      - /run/udev/data:/run/udev/data
    ports:
      - 3000:3000
      - 443:443
    restart: unless-stopped
